# Generated by Django 4.1.7 on 2023-05-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_auto_20230501_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datos.question')),
            ],
            bases=('datos.question',),
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datos.question')),
            ],
            bases=('datos.question',),
        ),
        migrations.CreateModel(
            name='Question4',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datos.question')),
            ],
            bases=('datos.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='content2',
            field=models.TextField(default=''),
        ),
    ]
