# Generated by Django 3.1.1 on 2023-05-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_question2_question3_question4_question_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
