# Generated by Django 3.1.1 on 2023-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
