# Generated by Django 3.1.1 on 2023-05-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0010_images2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
